### ISSUE TITLE
Convex factorization machines

### ISSUE THREAD

**Issue by neonnnnn** [neonnnnn/nimfm#7]
It would be very nice to implement convex factorization machines.

## TODO
- [x] Convex FMs
- [x] Solvers
  - [x] [Diagonal refitting greedy CD](http://mblondel.org/publications/mblondel-ecmlpkdd2015.pdf)
  - [x] [Fully refitting greedy CD](http://mblondel.org/publications/mblondel-ecmlpkdd2015.pdf)
  - [x] [Hazan for regression](https://riken-yamada.github.io/paper/KDD_2017_errata.pdf)
